// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoEhnsbqfBa-fFe72hBxooK1uq9_XRbh8',
    appId: '1:65130572543:android:6ea3d5a5e6d8eaf01cbaca',
    messagingSenderId: '65130572543',
    projectId: 'flutter-chat-firebase-9e7b0',
    databaseURL: 'https://flutter-chat-firebase-9e7b0-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-firebase-9e7b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA25nE8G5UdBUblnPOVCDDZpyT509bYQD0',
    appId: '1:65130572543:ios:25e31e9b9893451b1cbaca',
    messagingSenderId: '65130572543',
    projectId: 'flutter-chat-firebase-9e7b0',
    databaseURL: 'https://flutter-chat-firebase-9e7b0-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-firebase-9e7b0.appspot.com',
    iosBundleId: 'com.nmustakim.jobEstate',
  );
}
