class Lists {
  List<String> employmentType = ['Full time', 'Part time', 'Contractual'];

  List<String> organizationType = [
    'Design',
    'Software',
    'Accounting',
    'Engineering'
  ];
  List<String> genderType = ['Male', 'Female'];
  List<String> userType = ['Employer', 'Employee'];
  List<String> educationalDegrees = [
    'BE in Civil Engineering',
    'BE in Mechanical Engineering',
    'BE in Electrical Engineering',
    'BE in Computer Engineering',
    'BE in Chemical Engineering',
    'BE in Aerospace Engineering',
    'BE in Software Engineering',
    'BE in Biomedical Engineering',
    'ME in Civil Engineering',
    'ME in Mechanical Engineering',
    'ME in Electrical Engineering',
    'ME in Computer Engineering',
    'ME in Chemical Engineering',
    'ME in Aerospace Engineering',
    'ME in Software Engineering',
    'ME in Biomedical Engineering',
    'BSc. in Physics',
    'BSc. in Chemistry',
    'BSc. in Mathematics',
    'BSc. in Computer Science',
    'BSc. in Environmental Science',
    'BSc. in Physics',
    'BSc. in Statistics',
    'MSc. in Physics',
    'MSc. in Chemistry',
    'MSc. in Mathematics',
    'MSc. in Computer Science',
    'MSc. in Environmental Science',
    'MSc. in Physics',
    'MSc. in Statistics',
    'BBA',
    'Bachelor of Commerce',
    'Bachelor of Economics',
    'Bachelor of Accounting',
    'Bachelor of Finance',
    'Master of Business Administration',
    'Master of Commerce',
    'Master of Economics',
    'Master of Accounting',
    'Master of Finance',
    'BTech',
    'MTech',
    'BA in Hotel Management',
    'MA in of Hotel Management',
    'BA in Graphic Design',
    'MA in Graphic Design',
  ];

  List<String> skills = [
    'Graphic Design',
    'Typography',
    'Branding',
    'User Interface Design',
    'Web Design',
    'Illustration',
    'Animation',
    'Photography',
    'Video Editing',
    'Software'
        'Python',
    'Java',
    'C#',
    'JavaScript',
    'IDEs',
    'Version Control Systems',
    'Agile',
    'Scrum',
    'Unit Testing',
    'Debugging Tools',
    'Algebra',
    'Calculus',
    'Trigonometry',
    'Engineering Ethics',
    'Safety Regulations',
    'CAD/CAM Software',
    'Engineering Project Management',
    'Teamwork Skills',
    'GAAP',
    'IFRS',
    'QuickBooks',
    'Excel',
    'Balance Sheet',
    'Income Statement',
    'Accounting Research',
    'Analysis Skills',
  ];
}
